# Generated by Django 3.0 on 2019-12-18 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='product_image',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='service_image',
        ),
    ]
