# Generated by Django 3.0 on 2020-02-17 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20191218_1252'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
