# Generated by Django 3.0 on 2020-02-20 03:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='product_photo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='picture'),
            preserve_default=False,
        ),
    ]
